dist: xenial
language: python
compiler:
  - gcc
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
install:
 - pip install -r requirements-${PROF}.txt
 - ./build-deps.sh
script:
 - make PYTHON=`which python` -j2 CMD_CPPFLAGS="-Wall -Werror=implicit-function-declaration"
 - if [ "$TEST" = "YES" ]; then make PYTHON=`which python` -j2 nose; fi
matrix:
  include:
  - python: "2.7"
    env: BRBASE=7.0 PROF=deb8 TEST=YES
  - python: "3.4"
    env: BRBASE=7.0 PROF=deb8 TEST=YES
  - python: "3.5"
    env: BRBASE=7.0 PROF=deb9 TEST=YES
  - python: "3.6"
    env: BRBASE=7.0 PROF=deb9 TEST=YES
  - python: "3.7"
    env: BRBASE=7.0 PROF=deb10 TEST=YES
  - python: "2.7"
    env: BRBASE=3.16 PROF=deb8 TEST=YES
  - python: "2.7"
    env: BRBASE=3.15 PROF=deb8 TEST=YES
  - python: "2.7"
    env: BRBASE=3.14 PROF=deb8
